[package]
name = "gossip-glomers-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maelstrom-node = "0.1.6"
async-trait = "0.1.51"

[[bin]]
name = "echo"
path = "src/bin/echo.rs"
